The Tooba: Voice Class Reference
Voice Class Reference
#include <voice.h>
Public Member Functions
Voice ()
void step (void)
void setfreq (float f)
void keydown (uint32_t down)
int32_t output (void)
Data Fields
Oscillator osc1
Oscillator osc2
Oscillator osc3
ADSR adsr
Detailed Description
Definition at line 132 of file voice.h.
Constructor & Destructor Documentation
Voice::Voice () inline
Definition at line 137 of file voice.h.
Member Function Documentation
void Voice::keydown (uint32_t down) inline
Definition at line 157 of file voice.h.
Referenced by Key::check().
int32_t Voice::output (void) inline
Definition at line 160 of file voice.h.
void Voice::setfreq (float f) inline
Definition at line 152 of file voice.h.
Referenced by Key::check(), and main().
void Voice::step (void) inline
Definition at line 146 of file voice.h.
Field Documentation
ADSR Voice::adsr
Definition at line 135 of file voice.h.
Oscillator Voice::osc1
Definition at line 134 of file voice.h.
Oscillator Voice::osc2
Definition at line 134 of file voice.h.
Oscillator Voice::osc3
Definition at line 134 of file voice.h.
The documentation for this class was generated from the following file:
nextstage/teensy/voice.h