The Tooba: testit Namespace Reference
testit Namespace Reference
Variables
tuple q = instrument.Queue()
tuple x = q.read()
tuple osc = instrument.Oscillator()
tuple adsr = instrument.ADSR()
Variable Documentation
tuple testit.adsr = instrument.ADSR()
Definition at line 74 of file testit.py.
Referenced by Key.check(), and main().
tuple testit.osc = instrument.Oscillator()
Definition at line 34 of file testit.py.
tuple testit.q = instrument.Queue()
Definition at line 10 of file testit.py.
tuple testit.x = q.read()
Definition at line 14 of file testit.py.
Referenced by compute_sample(), get_12_bit_value(), Oscillator.output(), Voice.output(), Oscillator.setwaveform(), ADSR.step(), timer_interrupt(), and Queue.write().